apiVersion: v1 
kind: Service 
metadata:
  name: db
  labels: 
    app: postgres
    tier: postgres
    env: dev 
spec:
  ports:
    -  port: 5432 
       targetPort: 5432 
  selector:
    app: postgres
    tier: postgres
    env: dev 
