apiVersion: v1 
kind: Service 
metadata:
  name: redis
  labels: 
    app: redis
    tier: redis
    env: dev 
spec:
  ports:
    -  port: 6379 
       targetPort: 6379 
  selector:
    app: redis
    tier: redis
    env: dev 
