def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]

pipeline{
    agent { label "ub-jen" }
    tools {
        jdk "JDK17"
        maven "MAVEN3.9"
    }
    environment {
        USER_NAME = "admin"
        PASSWD = "password"
        SONAR_CUBE_SERVER = "sonarcube_server" 
        WAR_FILE = 'vprofile-v2.war'
        DOWNLOAD_URL = ""
        appRegistry = "ghcr.io/imazycool/vprofile"
        IMAGE_NAME = "ghcr.io/imazyccol/imazy-jenkins"
        IMAGE_TAG = "latest"
        FULL_IMAGE = "${IMAGE_NAME}:${IMAGE_TAG}"
        DOCKER_IMAGE = "ghcr.io/imazycool/vprofile"
        GHCR_CREDENTIALS = credentials('jenkins-ghcr.io') // Secret Text: GitHub PAT
    }
    stages {
        stage ("code checkout") {
            steps{
                git url: "https://github.com/imazycool/python.git" , branch:"docker"
            }
        }
        stage ("maven build") {
            steps {
                echo "####################################################"
                sh "java -version"
                echo "####################################################"
                script {
                    withEnv(['MAVEN_OPTS=-Xmx2048m -Xms1024m']) {
                        sh "mvn clean install -DskipTests"
                    }
                }
            }
            post{
                success{
                    echo "*********------- archieving artifacts ------->>>>>>> "
                    archiveArtifacts artifacts: "**/target/*.war"
                }
                failure{
                    echo 'Build failed. No artifacts will be archived.'
                    echo "###########################################################"
                }
            }
        }
        stage ("test") {
            steps{
                echo "###########################################################"
                sh "mvn test"
                echo "###########################################################"
            }
        }
        stage ("code analysis - checkstyle") {
            steps{
                echo "###########################################################"
                sh "mvn checkstyle:checkstyle"
            }
            post{
                success{
                    echo "###########################################################"
                    echo "checkstyle code analysis completed"
                }
            }
        }
        stage ("upload report sonarqube") {
            environment {
                scannerHome = tool 'SONAR6.2'
            }
            steps {
                withSonarQubeEnv("${SONAR_CUBE_SERVER}") {
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=imazy-jenkins-project \
                   -Dsonar.projectName=vprofile \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                }
            }
        }
        
        stage ("get archieve path"){
            steps{
                script {
                    def jobName = env.JOB_NAME.replaceAll('%2F', '/')
                    def buildNumber = env.BUILD_NUMBER
                    def artifactName = 'target/vprofile-v2.war'
                    env.jen_home = "${env.JENKINS_HOME}"
                    env.artifact_file = "${env.jen_home}/jobs/${jobName}/builds/${buildNumber}/archive/${artifactName}"
                    echo "Artifact Download URL: ${env.artifact_file}"
                }
            }
        }

        stage('Build App Image') {
            steps {
                script {
                    echo "XXXXXXXXXXXX------   Cleaning all local Docker images...-------XXXXXXXXXXXXX "
                    sh "docker image prune -af || true"
                    def dockerImage = docker.build("${appRegistry}:${BUILD_NUMBER}", "--build-arg MAVEN_OPTS='-Xmx2048m' ./Docker-files/app/multistage/")
                    sh "docker images"
                }
            }
        }

       stage('Image Push to GHCR') {
            steps {
                withCredentials([string(credentialsId: 'GHCR_TOKEN', variable: 'TOKEN')]) {
                    script {
                        sh "echo GHCR_TOKEN=\$TOKEN" 
                        sh """
                            echo "\$TOKEN" | docker login ghcr.io -u imazycool --password-stdin
                            docker push ${appRegistry}:${BUILD_NUMBER}
                        """
                    }
                }
            }
        }
                
        stage ("export var file to nexus") {
            steps{
                echo "###########################################################"
                sh "ls -ltr target/"
                sh "file target/vprofile-v2.war"
                sh "file --mime-type target/vprofile-v2.war"
                echo "###########################################################"
                nexusArtifactUploader(
                    nexusVersion: "nexus3" ,
                    protocol: "http" ,
                    nexusUrl: "192.168.223.139:8081" , 
                    groupId: "nexus-qa" ,
                    version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}" ,
                    repository: "imazy-repo" ,
                    // RepositoryId of the Repository in Nexus to which this artifact to be uploaded.
                    credentialsId: "nexus_repo" ,
                    artifacts: [
                        // Array / List of Nested Object
                        [artifactId: "imazy-vp" ,
                        classifier: '',
                        type: "war" ,
                        file: "target/vprofile-v2.war" ]
                    ]
                )
            }
        }

        stage('Clean created Docker Images') {
            steps {
                script {
                    echo "Cleaning all local Docker images..."
                    sh '''
                        docker image prune -af || true
                    '''
                }
            }
        }
        
    }
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#all-imazy-devops',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}


  