// pipeline {
//   agent any
//   stages {
//         stage('Checkout') {
//           steps {
//             git url: "https://github.com/hkhcoder/vprofile-project.git", branch: "atom" 
//          }
//     }
//   }
// }


// stages {
//         stage('Checkout') {
//           steps {
//             git url: "https://github.com/hkhcoder/vprofile-project.git", branch: "atom" 
//          }
//     }
//   }

pipeline{
    agent { label "ub-jen" }
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
        git "Default"
    }
    environment{
        USER_NAME = "admin"
        PASSWORD = "4223"
        MY_TEXT = "hello world from environment"
        SONARQUBE_ENV = "SONAR6.2"
    }
    stages{
        stage('Checkout') {
          steps {
            git url: "https://github.com/hkhcoder/vprofile-project.git", branch: "atom" 
          }
        }       
        stage('BUILD'){
            steps {
                echo "####################################################"
                sh "java -version"
                echo "####################################################"
                script {
                    withEnv(['MAVEN_OPTS=-Xmx2048m -Xms1024m']) {
                        sh 'mvn clean install -DskipTests'
                    }
                }
            }
            post {
                success {
                    echo "Now Archiving..."
                    archiveArtifacts artifacts: "**/target/*.war"
                }
                failure {
                    echo 'Build failed. No artifacts will be archived.'
                }
            }
        }

        stage ("TEST"){
            steps{
                sh "mvn clean test"
            }
        }

        stage ('CODE ANALYSIS WITH CHECKSTYLE'){
            steps {
                sh 'mvn checkstyle:checkstyle'
            }
            post {
                success {
                    echo 'Generated Analysis Result'
                }
            }
        }
    }
}