pipeline {
    agent { label "ub-jen" }
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }
    environment{
        USER_NAME = "admin"
        PASSWORD = ""
        MY_TEXT = "hello world from environment"
        SONARQUBE_ENV = tool "SONAR6.2"
        SONAR_CUBE_SERVER ="sonarcube_server"
    }
    stages{
        stage ("code checkout") {
            steps{
                git branch: "atom" , url:"https://github.com/hkhcoder/vprofile-project.git" 
            }
        }

        stage('BUILD'){
            steps {
                echo "####################################################"
                sh "java -version"
                echo "####################################################"
                script {
                    withEnv(['MAVEN_OPTS=-Xmx2048m -Xms1024m']) {
                        mvn clean install -DskipTests
                    }
                }
            }
            post {
                success {
                    echo "Now Archiving..."
                    archiveArtifacts artifacts: "**/target/*.war"
                }
                failure {
                    echo 'Build failed. No artifacts will be archived.'
                }
            }
        }

        stage ("TEST"){
            steps{
                sh "mvn clean test"
            }
        }

        stage ('CODE ANALYSIS WITH CHECKSTYLE'){
            steps {
                sh 'mvn checkstyle:checkstyle'
            }
            post {
                success {
                    echo 'Generated Analysis Result'
                }
            }
        }
        stage('SonarQube Scan') {
            environment {
                scannerHome = tool 'SONAR6.2'
            }
            steps {
                withSonarQubeEnv("${SONAR_CUBE_SERVER}") {
                    sh """ ${scannerHome}/bin/sonar-scanner  -Dsonar.projectKey=imazy-jenkins-project \
                      -Dsonar.sources=. \
                      -Dsonar.java.binaries=target/classes
                    """
                }
            }
        }
    }
}