apiVersion: v1
kind: Service 
metadata: 
  name: http-service
  labels:
    app: http-app-service 
    env: dev
spec:
  type: NodePort 
  ports:
    -  port: 80
       targetPort: 80
       nodePort: 30008
  selector:
    apps: nginx-app
       

