apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    env: dev 
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1        # Max unavailable Pods during update
    #   maxSurge: 1      # Max extra Pods above desired count during update
  template:
    metadata:
      labels:
        apps: nginx-app
    spec:
      containers: 
        -  name: nginx
           image: nginx
  selector:
    matchLabels:
      apps: nginx-app
