Vagrant.configure("2") do |config|
config.vm.box = "spox/ubuntu-arm"
config.vm.box_version = "1.0.0"
config.vm.network "private_network", ip: "192.168.56.11"
config.vm.provider "vmware_desktop" do |vmware|
vmware.gui = true
vmware.memory = "3072"  
vmware.allowlist_verified = true
end
 config.vm.provision "shell", inline: <<-SHELL
    sudo ip addr flush dev eth0
    sudo ip addr add 192.168.223.200/24 dev eth0
    sudo ip link set eth0 up
  SHELL
config.vm.network "private_network", ip: "192.168.56.11"
end
